### PR TITLE
Show vs. statistics on players profile

### PR DESCRIPTION
**Pull request by mathijsclaassen**

### CODE REVIEW

**Comment by apetresc** [comment]
I'll test this out today! :) Sounds like an awesome feature.

**Comment by apetresc** [comment]
I've made some minor fixes, described in the commit messages. @mathijsclaassen, if you approve of these changes, I'm ready to merge and deploy to the web stores :)

**Comment by apetresc** [comment]
May I add that this is an absolutely *awesome* addition, and I'm very grateful for it!

**Comment by mathijsclaassen** [comment]
Super! Thanks for the review and fixes!

**Comment by apetresc** [comment]
I will release this today; I just have a few small performance improvements in the normal code that I want to roll into this release too, which I will get to this evening.

**Comment by apetresc** [comment]
This PR, and some performance improvements for chess/shogi board styles, have been pushed to Chrome and Firefox, and should be live in the next few minutes :) Cheers!

**Pull request merged**
